### Send POST request with json body
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 0
}

### Send POST request with json body
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "100000002"
}
